"""add_venues

Revision ID: 545ce1d45933
Revises: 39d3375336d1
Create Date: 2026-07-15 16:39:55.791765
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '545ce1d45933'
down_revision: Union[str, None] = '39d3375336d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('clubs', sa.Column('primary_venue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clubs', 'venues', ['primary_venue_id'], ['id'])
    op.drop_index('ix_competitions_external_id_year', table_name='competitions')
    op.drop_index('ix_competitions_external_id', table_name='competitions')
    op.create_index(op.f('ix_competitions_external_id'), 'competitions', ['external_id'], unique=True)
    op.add_column('games', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_games_venue_id'), 'games', ['venue_id'], unique=False)
    op.create_foreign_key(None, 'games', 'venues', ['venue_id'], ['id'])
    
    # --- Data Seeding and Mapping ---
    bind = op.get_bind()
    
    # 1. Gather unique location names from games and clubs
    res_games = bind.execute(sa.text("SELECT DISTINCT location FROM games WHERE location IS NOT NULL AND location != ''"))
    res_clubs = bind.execute(sa.text("SELECT DISTINCT home_ground_name FROM clubs WHERE home_ground_name IS NOT NULL AND home_ground_name != ''"))
    
    locations = set()
    for row in res_games.fetchall():
        locations.add(row[0])
    for row in res_clubs.fetchall():
        locations.add(row[0])
        
    # 2. Insert locations into venues table
    for loc in sorted(locations):
        bind.execute(
            sa.text("INSERT INTO venues (name) VALUES (:name) ON CONFLICT (name) DO NOTHING"),
            {"name": loc}
        )
        
    # 3. Update games to link to venues
    bind.execute(
        sa.text("UPDATE games SET venue_id = v.id FROM venues v WHERE games.location = v.name")
    )
    
    # 4. Update clubs to link to venues
    bind.execute(
        sa.text("UPDATE clubs SET primary_venue_id = v.id FROM venues v WHERE clubs.home_ground_name = v.name")
    )
    # --------------------------------
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_index(op.f('ix_games_venue_id'), table_name='games')
    op.drop_column('games', 'venue_id')
    op.drop_index(op.f('ix_competitions_external_id'), table_name='competitions')
    op.create_index('ix_competitions_external_id', 'competitions', ['external_id'], unique=False)
    op.create_index('ix_competitions_external_id_year', 'competitions', ['external_id', 'year'], unique=True)
    op.drop_constraint(None, 'clubs', type_='foreignkey')
    op.drop_column('clubs', 'primary_venue_id')
    op.drop_table('venues')
    # ### end Alembic commands ###
