"""add_pwa_subscriptions

Revision ID: 87061ea97c04
Revises: fad440b7be87
Create Date: 2026-05-31 16:09:16.762004
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87061ea97c04'
down_revision: Union[str, None] = 'fad440b7be87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pwa_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('p256dh', sa.String(length=300), nullable=False),
    sa.Column('auth', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pwa_subscriptions_endpoint'), 'pwa_subscriptions', ['endpoint'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pwa_subscriptions_endpoint'), table_name='pwa_subscriptions')
    op.drop_table('pwa_subscriptions')
    # ### end Alembic commands ###
