"""add_game_squads_and_player_impact_scores

Revision ID: c3cac01c502c
Revises: c71be23dadfe
Create Date: 2026-07-20 15:30:50.048895
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3cac01c502c'
down_revision: Union[str, None] = 'c71be23dadfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_impact_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('competition_mapping_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('games_with', sa.Integer(), nullable=False),
    sa.Column('games_without', sa.Integer(), nullable=False),
    sa.Column('win_rate_with', sa.Float(), nullable=True),
    sa.Column('win_rate_without', sa.Float(), nullable=True),
    sa.Column('margin_diff', sa.Float(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=False),
    sa.Column('last_calculated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['competition_mapping_id'], ['competition_mapping.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'team_id', 'year', name='uq_player_impact_scores_player_team_year')
    )
    op.create_index(op.f('ix_player_impact_scores_club_id'), 'player_impact_scores', ['club_id'], unique=False)
    op.create_index(op.f('ix_player_impact_scores_competition_mapping_id'), 'player_impact_scores', ['competition_mapping_id'], unique=False)
    op.create_index(op.f('ix_player_impact_scores_player_id'), 'player_impact_scores', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_impact_scores_team_id'), 'player_impact_scores', ['team_id'], unique=False)
    op.create_index(op.f('ix_player_impact_scores_year'), 'player_impact_scores', ['year'], unique=False)
    op.create_table('game_squads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_number', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'team_id', 'player_id', name='uq_game_squads_game_team_player')
    )
    op.create_index(op.f('ix_game_squads_game_id'), 'game_squads', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_squads_player_id'), 'game_squads', ['player_id'], unique=False)
    op.create_index(op.f('ix_game_squads_team_id'), 'game_squads', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_squads_team_id'), table_name='game_squads')
    op.drop_index(op.f('ix_game_squads_player_id'), table_name='game_squads')
    op.drop_index(op.f('ix_game_squads_game_id'), table_name='game_squads')
    op.drop_table('game_squads')
    op.drop_index(op.f('ix_player_impact_scores_year'), table_name='player_impact_scores')
    op.drop_index(op.f('ix_player_impact_scores_team_id'), table_name='player_impact_scores')
    op.drop_index(op.f('ix_player_impact_scores_player_id'), table_name='player_impact_scores')
    op.drop_index(op.f('ix_player_impact_scores_competition_mapping_id'), table_name='player_impact_scores')
    op.drop_index(op.f('ix_player_impact_scores_club_id'), table_name='player_impact_scores')
    op.drop_table('player_impact_scores')
    # ### end Alembic commands ###
