"""add_team_rating_history

Revision ID: c71be23dadfe
Revises: 545ce1d45933
Create Date: 2026-07-20 14:12:45.961476
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71be23dadfe'
down_revision: Union[str, None] = '545ce1d45933'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_rating_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('competition_mapping_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('rating_before', sa.Float(), nullable=False),
    sa.Column('rating_after', sa.Float(), nullable=False),
    sa.Column('opponent_team_id', sa.Integer(), nullable=False),
    sa.Column('opponent_rating', sa.Float(), nullable=False),
    sa.Column('expected_result', sa.Float(), nullable=False),
    sa.Column('actual_result', sa.Float(), nullable=False),
    sa.Column('home_advantage_applied', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['competition_mapping_id'], ['competition_mapping.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['opponent_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_rating_history_club_id'), 'team_rating_history', ['club_id'], unique=False)
    op.create_index(op.f('ix_team_rating_history_competition_mapping_id'), 'team_rating_history', ['competition_mapping_id'], unique=False)
    op.create_index(op.f('ix_team_rating_history_game_id'), 'team_rating_history', ['game_id'], unique=False)
    op.create_index(op.f('ix_team_rating_history_opponent_team_id'), 'team_rating_history', ['opponent_team_id'], unique=False)
    op.create_index(op.f('ix_team_rating_history_team_id'), 'team_rating_history', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_rating_history_team_id'), table_name='team_rating_history')
    op.drop_index(op.f('ix_team_rating_history_opponent_team_id'), table_name='team_rating_history')
    op.drop_index(op.f('ix_team_rating_history_game_id'), table_name='team_rating_history')
    op.drop_index(op.f('ix_team_rating_history_competition_mapping_id'), table_name='team_rating_history')
    op.drop_index(op.f('ix_team_rating_history_club_id'), table_name='team_rating_history')
    op.drop_table('team_rating_history')
    # ### end Alembic commands ###
