"""add_pwa_subscription_topics

Revision ID: dd8f46a15a42
Revises: 87061ea97c04
Create Date: 2026-06-01 11:56:07.682580
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd8f46a15a42'
down_revision: Union[str, None] = '87061ea97c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pwa_subscription_topics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('topic_type', sa.String(length=50), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('notify_outcome', sa.Boolean(), nullable=False),
    sa.Column('notify_events', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['pwa_subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscription_id', 'topic_type', 'topic_id', name='uq_subscription_topic')
    )
    op.create_index(op.f('ix_pwa_subscription_topics_subscription_id'), 'pwa_subscription_topics', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pwa_subscription_topics_subscription_id'), table_name='pwa_subscription_topics')
    op.drop_table('pwa_subscription_topics')
    # ### end Alembic commands ###
