"""add_video_url_to_games

Revision ID: fad440b7be87
Revises: f7cde3f727d1
Create Date: 2026-05-25 13:36:14.624651
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fad440b7be87'
down_revision: Union[str, None] = 'f7cde3f727d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('competitions_external_id_key', 'competitions', type_='unique')
    op.drop_index('ix_competitions_external_id', table_name='competitions')
    op.create_index(op.f('ix_competitions_external_id'), 'competitions', ['external_id'], unique=True)
    op.add_column('games', sa.Column('video_url', sa.String(length=500), nullable=True))
    op.add_column('games', sa.Column('video_url_needs_review', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_constraint('games_external_id_key', 'games', type_='unique')
    op.drop_index('ix_games_external_id', table_name='games')
    op.create_index(op.f('ix_games_external_id'), 'games', ['external_id'], unique=True)
    op.drop_constraint('player_history_game_id_fkey', 'player_history', type_='foreignkey')
    op.drop_constraint('player_history_player_id_fkey', 'player_history', type_='foreignkey')
    op.drop_constraint('player_history_team_id_fkey', 'player_history', type_='foreignkey')
    op.create_foreign_key(None, 'player_history', 'games', ['game_id'], ['id'])
    op.create_foreign_key(None, 'player_history', 'players', ['player_id'], ['id'])
    op.create_foreign_key(None, 'player_history', 'teams', ['team_id'], ['id'])
    op.drop_constraint('players_external_id_key', 'players', type_='unique')
    op.drop_index('ix_players_external_id', table_name='players')
    op.create_index(op.f('ix_players_external_id'), 'players', ['external_id'], unique=True)
    op.drop_constraint('rounds_external_id_key', 'rounds', type_='unique')
    op.drop_index('ix_rounds_external_id', table_name='rounds')
    op.create_index(op.f('ix_rounds_external_id'), 'rounds', ['external_id'], unique=True)
    op.drop_constraint('teams_external_id_key', 'teams', type_='unique')
    op.drop_index('ix_teams_external_id', table_name='teams')
    op.create_index(op.f('ix_teams_external_id'), 'teams', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_external_id'), table_name='teams')
    op.create_index('ix_teams_external_id', 'teams', ['external_id'], unique=False)
    op.create_unique_constraint('teams_external_id_key', 'teams', ['external_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_rounds_external_id'), table_name='rounds')
    op.create_index('ix_rounds_external_id', 'rounds', ['external_id'], unique=False)
    op.create_unique_constraint('rounds_external_id_key', 'rounds', ['external_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_players_external_id'), table_name='players')
    op.create_index('ix_players_external_id', 'players', ['external_id'], unique=False)
    op.create_unique_constraint('players_external_id_key', 'players', ['external_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'player_history', type_='foreignkey')
    op.drop_constraint(None, 'player_history', type_='foreignkey')
    op.drop_constraint(None, 'player_history', type_='foreignkey')
    op.create_foreign_key('player_history_team_id_fkey', 'player_history', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('player_history_player_id_fkey', 'player_history', 'players', ['player_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('player_history_game_id_fkey', 'player_history', 'games', ['game_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_games_external_id'), table_name='games')
    op.create_index('ix_games_external_id', 'games', ['external_id'], unique=False)
    op.create_unique_constraint('games_external_id_key', 'games', ['external_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('games', 'video_url_needs_review')
    op.drop_column('games', 'video_url')
    op.drop_index(op.f('ix_competitions_external_id'), table_name='competitions')
    op.create_index('ix_competitions_external_id', 'competitions', ['external_id'], unique=False)
    op.create_unique_constraint('competitions_external_id_key', 'competitions', ['external_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
