import { precacheAndRoute } from 'workbox-precaching'

// Precache assets generated by build
precacheAndRoute(self.__WB_MANIFEST)

// Listen to push events
self.addEventListener('push', (event) => {
  if (!event.data) return

  try {
    const data = event.data.json()
    const title = data.title || 'Subbies Live Update'
    const options = {
      body: data.body || '',
      icon: '/pwa-192x192.png',
      badge: '/favicon.ico',
      tag: data.tag || undefined,
      renotify: data.tag ? true : false,
      data: {
        url: data.url || '/'
      }
    }
    event.waitUntil(
      self.registration.showNotification(title, options)
    )
  } catch (err) {
    const text = event.data.text()
    const options = {
      body: text,
      icon: '/pwa-192x192.png',
      badge: '/favicon.ico',
      data: {
        url: '/'
      }
    }
    event.waitUntil(
      self.registration.showNotification('Subbies Live Update', options)
    )
  }
})

// Listen to notification click events to open/focus PWA
self.addEventListener('notificationclick', (event) => {
  event.notification.close()

  const urlToOpen = new URL(event.notification.data.url, self.location.origin).href

  event.waitUntil(
    clients.matchAll({
      type: 'window',
      includeUncontrolled: true
    }).then((windowClients) => {
      // Send NAVIGATE message to existing window client and focus it
      for (let i = 0; i < windowClients.length; i++) {
        const client = windowClients[i]
        if (client.url.startsWith(self.location.origin) && 'focus' in client) {
          client.postMessage({ type: 'NAVIGATE', url: urlToOpen })
          return client.focus()
        }
      }
      // Open new window if none exists
      if (clients.openWindow) {
        return clients.openWindow(urlToOpen)
      }
    })
  )
})

// Listen for SKIP_WAITING message to activate the new service worker
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting()
  }
})
